[2023-08-24T01:07:24.569+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 14_group_and_label.TaskGroup.task_inner2 manual__2023-08-24T01:07:16.457503+00:00 [queued]>
[2023-08-24T01:07:24.588+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 14_group_and_label.TaskGroup.task_inner2 manual__2023-08-24T01:07:16.457503+00:00 [queued]>
[2023-08-24T01:07:24.588+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-24T01:07:24.614+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): TaskGroup.task_inner2> on 2023-08-24 01:07:16.457503+00:00
[2023-08-24T01:07:24.625+0000] {standard_task_runner.py:57} INFO - Started process 2419 to run task
[2023-08-24T01:07:24.629+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '14_group_and_label', 'TaskGroup.task_inner2', 'manual__2023-08-24T01:07:16.457503+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/14_group_and_label.py', '--cfg-path', '/tmp/tmpqv8x97bo']
[2023-08-24T01:07:24.631+0000] {standard_task_runner.py:85} INFO - Job 189: Subtask TaskGroup.task_inner2
[2023-08-24T01:07:24.689+0000] {task_command.py:410} INFO - Running <TaskInstance: 14_group_and_label.TaskGroup.task_inner2 manual__2023-08-24T01:07:16.457503+00:00 [running]> on host 05c492c53b17
[2023-08-24T01:07:24.790+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='14_group_and_label' AIRFLOW_CTX_TASK_ID='TaskGroup.task_inner2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T01:07:16.457503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T01:07:16.457503+00:00'
[2023-08-24T01:07:24.792+0000] {logging_mixin.py:150} INFO - TaskGroup의 두 번째 task
[2023-08-24T01:07:24.792+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-24T01:07:24.804+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=14_group_and_label, task_id=TaskGroup.task_inner2, execution_date=20230824T010716, start_date=20230824T010724, end_date=20230824T010724
[2023-08-24T01:07:24.842+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-24T01:07:24.866+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
