[2023-08-23T22:58:53.516+0000] {processor.py:157} INFO - Started process (PID=3004) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T22:58:53.517+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T22:58:53.518+0000] {logging_mixin.py:150} INFO - [2023-08-23T22:58:53.518+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T22:58:53.527+0000] {logging_mixin.py:150} INFO - [2023-08-23T22:58:53.524+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T22:58:53.528+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T22:58:53.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T22:59:13.225+0000] {processor.py:157} INFO - Started process (PID=3033) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T22:59:13.226+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T22:59:13.227+0000] {logging_mixin.py:150} INFO - [2023-08-23T22:59:13.227+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T22:59:13.236+0000] {logging_mixin.py:150} INFO - [2023-08-23T22:59:13.234+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T22:59:13.237+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T22:59:13.268+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.047 seconds
[2023-08-23T22:59:43.560+0000] {processor.py:157} INFO - Started process (PID=3094) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T22:59:43.562+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T22:59:43.563+0000] {logging_mixin.py:150} INFO - [2023-08-23T22:59:43.562+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T22:59:43.574+0000] {logging_mixin.py:150} INFO - [2023-08-23T22:59:43.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T22:59:43.574+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T22:59:43.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:00:06.403+0000] {processor.py:157} INFO - Started process (PID=3155) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:00:06.404+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:00:06.405+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:00:06.405+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:00:06.413+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:00:06.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:00:06.414+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:00:06.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:00:36.980+0000] {processor.py:157} INFO - Started process (PID=3216) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:00:36.986+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:00:36.988+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:00:36.987+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:00:36.994+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:00:36.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:00:36.995+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:00:37.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:01:07.341+0000] {processor.py:157} INFO - Started process (PID=3277) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:01:07.341+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:01:07.342+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:01:07.342+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:01:07.348+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:01:07.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:01:07.348+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:01:07.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:01:37.805+0000] {processor.py:157} INFO - Started process (PID=3338) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:01:37.807+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:01:37.808+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:01:37.808+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:01:37.818+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:01:37.816+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:01:37.819+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:01:37.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.052 seconds
[2023-08-23T23:02:08.656+0000] {processor.py:157} INFO - Started process (PID=3399) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:02:08.657+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:02:08.658+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:02:08.658+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:02:08.665+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:02:08.663+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:02:08.666+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:02:08.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.047 seconds
[2023-08-23T23:02:39.018+0000] {processor.py:157} INFO - Started process (PID=3460) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:02:39.020+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:02:39.020+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:02:39.020+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:02:39.026+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:02:39.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:02:39.026+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:02:39.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:03:09.761+0000] {processor.py:157} INFO - Started process (PID=3521) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:03:09.764+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:03:09.765+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:03:09.765+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:03:09.770+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:03:09.769+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:03:09.771+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:03:09.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.049 seconds
[2023-08-23T23:03:40.224+0000] {processor.py:157} INFO - Started process (PID=3582) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:03:40.225+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:03:40.226+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:03:40.226+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:03:40.235+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:03:40.233+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:03:40.235+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:03:40.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.052 seconds
[2023-08-23T23:04:11.184+0000] {processor.py:157} INFO - Started process (PID=3643) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:04:11.191+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:04:11.193+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:04:11.192+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:04:11.202+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:04:11.200+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:04:11.203+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:04:11.242+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.063 seconds
[2023-08-23T23:04:41.876+0000] {processor.py:157} INFO - Started process (PID=3704) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:04:41.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:04:41.877+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:04:41.877+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:04:41.883+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:04:41.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:04:41.883+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:04:41.909+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:05:12.807+0000] {processor.py:157} INFO - Started process (PID=3765) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:05:12.809+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:05:12.810+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:05:12.810+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:05:12.816+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:05:12.814+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:05:12.816+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:05:12.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:05:42.982+0000] {processor.py:157} INFO - Started process (PID=3827) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:05:42.983+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:05:42.984+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:05:42.983+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:05:42.989+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:05:42.988+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:05:42.990+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:05:43.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:06:13.381+0000] {processor.py:157} INFO - Started process (PID=3888) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:06:13.389+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:06:13.390+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:06:13.389+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:06:13.395+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:06:13.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:06:13.395+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:06:13.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:06:43.713+0000] {processor.py:157} INFO - Started process (PID=3949) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:06:43.720+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:06:43.721+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:06:43.721+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:06:43.731+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:06:43.729+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:06:43.732+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:06:43.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.064 seconds
[2023-08-23T23:07:14.656+0000] {processor.py:157} INFO - Started process (PID=4010) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:07:14.663+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:07:14.664+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:07:14.664+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:07:14.670+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:07:14.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:07:14.670+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:07:14.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.041 seconds
[2023-08-23T23:07:45.450+0000] {processor.py:157} INFO - Started process (PID=4071) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:07:45.451+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:07:45.452+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:07:45.452+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:07:45.459+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:07:45.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:07:45.460+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:07:45.488+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:08:16.473+0000] {processor.py:157} INFO - Started process (PID=4132) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:08:16.474+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:08:16.475+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:08:16.475+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:08:16.480+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:08:16.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:08:16.480+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:08:16.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.032 seconds
[2023-08-23T23:08:46.641+0000] {processor.py:157} INFO - Started process (PID=4193) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:08:46.642+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:08:46.642+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:08:46.642+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:08:46.648+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:08:46.646+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:08:46.648+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:08:46.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.034 seconds
[2023-08-23T23:09:17.343+0000] {processor.py:157} INFO - Started process (PID=4254) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:09:17.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:09:17.350+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:09:17.350+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:09:17.357+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:09:17.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:09:17.357+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:09:17.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.044 seconds
[2023-08-23T23:09:47.823+0000] {processor.py:157} INFO - Started process (PID=4315) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:09:47.830+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:09:47.832+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:09:47.831+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:09:47.840+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:09:47.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:09:47.841+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:09:47.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.054 seconds
[2023-08-23T23:10:18.577+0000] {processor.py:157} INFO - Started process (PID=4376) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:10:18.577+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:10:18.578+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:10:18.578+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:10:18.584+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:10:18.583+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:10:18.584+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:10:18.608+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:10:48.948+0000] {processor.py:157} INFO - Started process (PID=4437) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:10:48.950+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:10:48.950+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:10:48.950+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:10:48.956+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:10:48.955+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:10:48.956+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:10:48.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.034 seconds
[2023-08-23T23:11:19.413+0000] {processor.py:157} INFO - Started process (PID=4498) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:11:19.415+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:11:19.415+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:11:19.415+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:11:19.421+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:11:19.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:11:19.421+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:11:19.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:11:50.103+0000] {processor.py:157} INFO - Started process (PID=4559) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:11:50.105+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:11:50.106+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:11:50.105+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:11:50.111+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:11:50.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:11:50.111+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:11:50.147+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.047 seconds
[2023-08-23T23:12:20.254+0000] {processor.py:157} INFO - Started process (PID=4620) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:12:20.255+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:12:20.257+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:12:20.257+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:12:20.263+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:12:20.262+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:12:20.264+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:12:20.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:12:50.338+0000] {processor.py:157} INFO - Started process (PID=4681) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:12:50.340+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:12:50.341+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:12:50.341+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:12:50.350+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:12:50.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:12:50.351+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:12:50.378+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.047 seconds
[2023-08-23T23:13:21.020+0000] {processor.py:157} INFO - Started process (PID=4742) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:13:21.021+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:13:21.022+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:13:21.022+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:13:21.038+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:13:21.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:13:21.039+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:13:21.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.050 seconds
[2023-08-23T23:13:51.429+0000] {processor.py:157} INFO - Started process (PID=4804) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:13:51.430+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:13:51.430+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:13:51.430+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:13:51.437+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:13:51.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:13:51.437+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:13:51.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:14:22.243+0000] {processor.py:157} INFO - Started process (PID=4867) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:14:22.244+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:14:22.245+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:14:22.245+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:14:22.251+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:14:22.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:14:22.252+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:14:22.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:14:52.515+0000] {processor.py:157} INFO - Started process (PID=4929) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:14:52.515+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:14:52.516+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:14:52.516+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:14:52.522+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:14:52.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:14:52.522+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:14:52.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:15:22.653+0000] {processor.py:157} INFO - Started process (PID=4991) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:15:22.655+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:15:22.656+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:15:22.656+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:15:22.665+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:15:22.664+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:15:22.665+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:15:22.691+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:15:53.102+0000] {processor.py:157} INFO - Started process (PID=5052) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:15:53.103+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:15:53.103+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:15:53.103+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:15:53.111+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:15:53.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:15:53.112+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:15:53.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:16:23.319+0000] {processor.py:157} INFO - Started process (PID=5113) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:16:23.321+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:16:23.322+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:16:23.321+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:16:23.331+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:16:23.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:16:23.332+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:16:23.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.044 seconds
[2023-08-23T23:16:54.160+0000] {processor.py:157} INFO - Started process (PID=5174) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:16:54.161+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:16:54.163+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:16:54.162+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:16:54.169+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:16:54.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:16:54.170+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:16:54.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.051 seconds
[2023-08-23T23:17:24.662+0000] {processor.py:157} INFO - Started process (PID=5235) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:17:24.664+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:17:24.665+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:17:24.665+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:17:24.672+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:17:24.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:17:24.672+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:17:24.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:17:54.855+0000] {processor.py:157} INFO - Started process (PID=5297) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:17:54.855+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:17:54.856+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:17:54.856+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:17:54.862+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:17:54.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:17:54.863+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:17:54.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:18:25.579+0000] {processor.py:157} INFO - Started process (PID=5358) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:18:25.585+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:18:25.586+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:18:25.586+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:18:25.593+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:18:25.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:18:25.593+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:18:25.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:18:56.113+0000] {processor.py:157} INFO - Started process (PID=5421) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:18:56.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:18:56.116+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:18:56.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:18:56.123+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:18:56.121+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:18:56.123+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:18:56.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:19:26.717+0000] {processor.py:157} INFO - Started process (PID=5484) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:19:26.718+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:19:26.719+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:19:26.719+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:19:26.726+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:19:26.724+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:19:26.726+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:19:26.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.034 seconds
[2023-08-23T23:19:57.216+0000] {processor.py:157} INFO - Started process (PID=5548) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:19:57.217+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:19:57.218+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:19:57.217+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:19:57.225+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:19:57.224+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:19:57.226+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:19:57.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:20:27.426+0000] {processor.py:157} INFO - Started process (PID=5611) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:20:27.428+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:20:27.428+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:20:27.428+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:20:27.436+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:20:27.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:20:27.436+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:20:27.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:20:57.813+0000] {processor.py:157} INFO - Started process (PID=5675) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:20:57.814+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:20:57.815+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:20:57.814+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:20:57.822+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:20:57.821+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:20:57.823+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:20:57.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:21:28.683+0000] {processor.py:157} INFO - Started process (PID=5738) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:21:28.685+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:21:28.687+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:21:28.686+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:21:28.696+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:21:28.695+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:21:28.697+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:21:28.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.048 seconds
[2023-08-23T23:21:59.442+0000] {processor.py:157} INFO - Started process (PID=5802) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:21:59.443+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:21:59.444+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:21:59.443+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:21:59.450+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:21:59.449+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:21:59.450+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:21:59.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:22:30.241+0000] {processor.py:157} INFO - Started process (PID=5865) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:22:30.244+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:22:30.245+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:22:30.244+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:22:30.253+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:22:30.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:22:30.253+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:22:30.285+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.048 seconds
[2023-08-23T23:23:00.469+0000] {processor.py:157} INFO - Started process (PID=5929) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:23:00.469+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:23:00.470+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:23:00.470+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:23:00.476+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:23:00.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:23:00.476+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:23:00.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.033 seconds
[2023-08-23T23:23:31.168+0000] {processor.py:157} INFO - Started process (PID=5992) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:23:31.174+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:23:31.175+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:23:31.175+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:23:31.186+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:23:31.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:23:31.186+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:23:31.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.051 seconds
[2023-08-23T23:24:01.947+0000] {processor.py:157} INFO - Started process (PID=6055) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:24:01.948+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:24:01.948+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:24:01.948+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:24:01.957+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:24:01.955+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:24:01.957+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:24:01.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:24:32.930+0000] {processor.py:157} INFO - Started process (PID=6118) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:24:32.937+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:24:32.938+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:24:32.938+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:24:32.950+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:24:32.948+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:24:32.951+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:24:32.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.052 seconds
[2023-08-23T23:25:03.138+0000] {processor.py:157} INFO - Started process (PID=6181) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:25:03.138+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:25:03.139+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:25:03.139+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:25:03.145+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:25:03.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:25:03.146+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:25:03.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:25:33.625+0000] {processor.py:157} INFO - Started process (PID=6244) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:25:33.631+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:25:33.632+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:25:33.632+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:25:33.639+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:25:33.637+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:25:33.640+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:25:33.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:26:03.985+0000] {processor.py:157} INFO - Started process (PID=6307) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:26:03.986+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:26:03.987+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:26:03.987+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:26:03.996+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:26:03.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:26:03.997+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:26:04.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.047 seconds
[2023-08-23T23:26:34.639+0000] {processor.py:157} INFO - Started process (PID=6370) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:26:34.641+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:26:34.642+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:26:34.641+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:26:34.649+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:26:34.648+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:26:34.649+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:26:34.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:27:05.076+0000] {processor.py:157} INFO - Started process (PID=6433) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:27:05.082+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:27:05.082+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:27:05.082+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:27:05.088+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:27:05.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:27:05.089+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:27:05.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:27:35.449+0000] {processor.py:157} INFO - Started process (PID=6496) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:27:35.450+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:27:35.452+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:27:35.451+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:27:35.461+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:27:35.459+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:27:35.461+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:27:35.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.041 seconds
[2023-08-23T23:28:05.655+0000] {processor.py:157} INFO - Started process (PID=6560) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:28:05.662+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:28:05.664+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:28:05.663+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:28:05.670+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:28:05.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:28:05.670+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:28:05.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:28:36.181+0000] {processor.py:157} INFO - Started process (PID=6623) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:28:36.183+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:28:36.184+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:28:36.184+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:28:36.190+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:28:36.189+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:28:36.190+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:28:36.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:29:06.661+0000] {processor.py:157} INFO - Started process (PID=6686) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:29:06.666+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:29:06.668+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:29:06.667+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:29:06.673+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:29:06.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:29:06.674+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:29:06.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:29:37.199+0000] {processor.py:157} INFO - Started process (PID=6750) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:29:37.199+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:29:37.200+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:29:37.200+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:29:37.207+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:29:37.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:29:37.208+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:29:37.231+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:30:07.546+0000] {processor.py:157} INFO - Started process (PID=6813) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:30:07.547+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:30:07.548+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:30:07.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:30:07.560+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:30:07.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:30:07.560+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:30:07.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:30:38.164+0000] {processor.py:157} INFO - Started process (PID=6876) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:30:38.165+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:30:38.166+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:30:38.165+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:30:38.172+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:30:38.170+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:30:38.173+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:30:38.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:31:08.687+0000] {processor.py:157} INFO - Started process (PID=6939) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:31:08.694+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:31:08.695+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:31:08.695+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:31:08.700+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:31:08.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:31:08.700+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:31:08.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:31:39.158+0000] {processor.py:157} INFO - Started process (PID=7008) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:31:39.158+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:31:39.159+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:31:39.159+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:31:39.168+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:31:39.166+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:31:39.168+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:31:39.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:32:09.618+0000] {processor.py:157} INFO - Started process (PID=7072) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:32:09.624+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:32:09.625+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:32:09.624+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:32:09.631+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:32:09.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:32:09.631+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:32:09.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:32:40.142+0000] {processor.py:157} INFO - Started process (PID=7135) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:32:40.145+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:32:40.147+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:32:40.146+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:32:40.161+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:32:40.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:32:40.163+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:32:40.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.062 seconds
[2023-08-23T23:33:10.783+0000] {processor.py:157} INFO - Started process (PID=7198) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:33:10.784+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:33:10.786+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:33:10.785+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:33:10.797+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:33:10.795+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:33:10.797+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:33:10.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.045 seconds
[2023-08-23T23:33:41.114+0000] {processor.py:157} INFO - Started process (PID=7261) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:33:41.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:33:41.115+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:33:41.115+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:33:41.121+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:33:41.119+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:33:41.121+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:33:41.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.041 seconds
[2023-08-23T23:34:11.823+0000] {processor.py:157} INFO - Started process (PID=7325) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:34:11.825+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:34:11.826+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:34:11.825+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:34:11.833+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:34:11.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:34:11.834+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:34:11.858+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:34:42.682+0000] {processor.py:157} INFO - Started process (PID=7390) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:34:42.683+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:34:42.683+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:34:42.683+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:34:42.689+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:34:42.688+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:34:42.690+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:34:42.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:35:13.109+0000] {processor.py:157} INFO - Started process (PID=7454) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:35:13.110+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:35:13.111+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:35:13.111+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:35:13.117+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:35:13.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:35:13.117+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:35:13.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.033 seconds
[2023-08-23T23:35:43.749+0000] {processor.py:157} INFO - Started process (PID=7518) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:35:43.755+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:35:43.756+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:35:43.755+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:35:43.762+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:35:43.760+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:35:43.763+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:35:43.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:36:14.641+0000] {processor.py:157} INFO - Started process (PID=7582) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:36:14.647+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:36:14.648+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:36:14.648+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:36:14.654+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:36:14.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:36:14.655+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:36:14.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.041 seconds
[2023-08-23T23:36:44.787+0000] {processor.py:157} INFO - Started process (PID=7646) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:36:44.789+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:36:44.790+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:36:44.789+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:36:44.796+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:36:44.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:36:44.796+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:36:44.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:37:15.208+0000] {processor.py:157} INFO - Started process (PID=7710) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:37:15.210+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:37:15.211+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:37:15.211+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:37:15.218+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:37:15.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:37:15.218+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:37:15.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:37:45.607+0000] {processor.py:157} INFO - Started process (PID=7775) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:37:45.609+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:37:45.611+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:37:45.610+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:37:45.616+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:37:45.615+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:37:45.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:37:45.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:38:15.921+0000] {processor.py:157} INFO - Started process (PID=7839) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:38:15.922+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:38:15.923+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:38:15.923+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:38:15.930+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:38:15.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:38:15.930+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:38:15.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:38:46.458+0000] {processor.py:157} INFO - Started process (PID=7903) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:38:46.459+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:38:46.461+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:38:46.460+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:38:46.467+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:38:46.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:38:46.467+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:38:46.492+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:39:17.391+0000] {processor.py:157} INFO - Started process (PID=7967) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:39:17.397+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:39:17.398+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:39:17.398+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:39:17.405+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:39:17.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:39:17.406+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:39:17.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:39:47.855+0000] {processor.py:157} INFO - Started process (PID=8031) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:39:47.856+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:39:47.857+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:39:47.857+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:39:47.864+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:39:47.862+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:39:47.864+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:39:47.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.041 seconds
[2023-08-23T23:40:18.335+0000] {processor.py:157} INFO - Started process (PID=8096) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:40:18.336+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:40:18.337+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:40:18.336+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:40:18.345+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:40:18.343+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:40:18.345+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:40:18.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:40:48.479+0000] {processor.py:157} INFO - Started process (PID=8160) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:40:48.481+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:40:48.482+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:40:48.481+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:40:48.488+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:40:48.487+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:40:48.489+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:40:48.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.146 seconds
[2023-08-23T23:41:19.029+0000] {processor.py:157} INFO - Started process (PID=8224) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:41:19.031+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:41:19.032+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:41:19.031+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:41:19.039+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:41:19.038+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:41:19.040+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:41:19.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:41:49.388+0000] {processor.py:157} INFO - Started process (PID=8288) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:41:49.394+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:41:49.395+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:41:49.394+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:41:49.401+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:41:49.400+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:41:49.402+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:41:49.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.052 seconds
[2023-08-23T23:42:20.304+0000] {processor.py:157} INFO - Started process (PID=8352) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:42:20.305+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:42:20.306+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:42:20.306+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:42:20.313+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:42:20.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:42:20.313+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:42:20.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:42:51.072+0000] {processor.py:157} INFO - Started process (PID=8416) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:42:51.077+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:42:51.078+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:42:51.078+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:42:51.084+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:42:51.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:42:51.084+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:42:51.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.041 seconds
[2023-08-23T23:43:21.530+0000] {processor.py:157} INFO - Started process (PID=8480) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:43:21.531+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:43:21.532+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:43:21.532+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:43:21.539+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:43:21.538+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:43:21.540+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:43:21.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.045 seconds
[2023-08-23T23:43:51.642+0000] {processor.py:157} INFO - Started process (PID=8544) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:43:51.648+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:43:51.650+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:43:51.649+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:43:51.655+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:43:51.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:43:51.656+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:43:51.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.040 seconds
[2023-08-23T23:44:22.404+0000] {processor.py:157} INFO - Started process (PID=8608) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:44:22.405+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:44:22.406+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:44:22.405+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:44:22.412+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:44:22.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:44:22.413+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:44:22.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:44:52.832+0000] {processor.py:157} INFO - Started process (PID=8672) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:44:52.834+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:44:52.835+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:44:52.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:44:52.842+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:44:52.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:44:52.843+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:44:52.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:45:23.626+0000] {processor.py:157} INFO - Started process (PID=8736) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:45:23.633+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:45:23.634+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:45:23.633+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:45:23.639+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:45:23.638+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:45:23.639+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:45:23.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.043 seconds
[2023-08-23T23:45:54.663+0000] {processor.py:157} INFO - Started process (PID=8800) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:45:54.663+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:45:54.664+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:45:54.664+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:45:54.671+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:45:54.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:45:54.671+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:45:54.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:46:25.365+0000] {processor.py:157} INFO - Started process (PID=8867) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:25.367+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:46:25.368+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:46:25.368+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:25.378+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:46:25.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:46:25.378+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:25.407+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.045 seconds
[2023-08-23T23:46:26.446+0000] {processor.py:157} INFO - Started process (PID=8868) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:26.447+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:46:26.448+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:46:26.448+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:26.462+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:46:26.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:46:26.463+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:26.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.101 seconds
[2023-08-23T23:46:56.861+0000] {processor.py:157} INFO - Started process (PID=8933) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:56.863+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:46:56.864+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:46:56.864+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:56.875+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:46:56.873+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:46:56.876+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:46:56.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.140 seconds
[2023-08-23T23:47:27.540+0000] {processor.py:157} INFO - Started process (PID=8997) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:47:27.540+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:47:27.541+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:47:27.541+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:47:27.547+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:47:27.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:47:27.547+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:47:27.571+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.034 seconds
[2023-08-23T23:47:57.820+0000] {processor.py:157} INFO - Started process (PID=9062) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:47:57.822+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:47:57.823+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:47:57.822+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:47:57.829+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:47:57.828+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:47:57.829+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:47:57.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:48:28.513+0000] {processor.py:157} INFO - Started process (PID=9126) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:48:28.515+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:48:28.516+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:48:28.516+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:48:28.522+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:48:28.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:48:28.522+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:48:28.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:48:58.618+0000] {processor.py:157} INFO - Started process (PID=9191) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:48:58.619+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:48:58.620+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:48:58.619+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:48:58.626+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:48:58.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:48:58.626+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:48:58.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.036 seconds
[2023-08-23T23:49:28.992+0000] {processor.py:157} INFO - Started process (PID=9255) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:49:28.994+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:49:28.995+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:49:28.994+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:49:29.001+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:49:29.000+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:49:29.001+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:49:29.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:49:59.669+0000] {processor.py:157} INFO - Started process (PID=9311) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:49:59.671+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:49:59.672+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:49:59.671+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:49:59.681+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:49:59.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:49:59.682+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:49:59.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.042 seconds
[2023-08-23T23:50:29.895+0000] {processor.py:157} INFO - Started process (PID=9368) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:50:29.895+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:50:29.896+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:50:29.896+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:50:29.902+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:50:29.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:50:29.902+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:50:29.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:51:00.362+0000] {processor.py:157} INFO - Started process (PID=9433) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:51:00.367+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:51:00.369+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:51:00.369+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:51:00.389+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:51:00.387+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:51:00.390+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:51:00.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.111 seconds
[2023-08-23T23:51:31.167+0000] {processor.py:157} INFO - Started process (PID=9498) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:51:31.168+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:51:31.169+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:51:31.169+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:51:31.176+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:51:31.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:51:31.177+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:51:31.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.043 seconds
[2023-08-23T23:52:01.465+0000] {processor.py:157} INFO - Started process (PID=9563) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:52:01.467+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:52:01.468+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:52:01.467+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:52:01.474+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:52:01.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:52:01.475+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:52:01.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:52:31.928+0000] {processor.py:157} INFO - Started process (PID=9628) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:52:31.929+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:52:31.930+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:52:31.930+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:52:31.936+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:52:31.935+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:52:31.936+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:52:31.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:53:02.541+0000] {processor.py:157} INFO - Started process (PID=9693) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:53:02.547+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:53:02.548+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:53:02.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:53:02.556+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:53:02.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:53:02.557+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:53:02.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.044 seconds
[2023-08-23T23:53:32.988+0000] {processor.py:157} INFO - Started process (PID=9758) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:53:32.989+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:53:32.990+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:53:32.990+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:53:32.996+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:53:32.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:53:32.997+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:53:33.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:54:03.555+0000] {processor.py:157} INFO - Started process (PID=9823) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:54:03.557+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:54:03.558+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:54:03.558+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:54:03.565+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:54:03.563+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:54:03.565+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:54:03.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.037 seconds
[2023-08-23T23:54:33.924+0000] {processor.py:157} INFO - Started process (PID=9888) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:54:33.924+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:54:33.925+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:54:33.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:54:33.934+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:54:33.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:54:33.934+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:54:33.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:55:04.337+0000] {processor.py:157} INFO - Started process (PID=9953) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:55:04.339+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:55:04.340+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:55:04.340+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:55:04.353+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:55:04.349+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:55:04.354+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:55:04.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.055 seconds
[2023-08-23T23:55:34.778+0000] {processor.py:157} INFO - Started process (PID=10018) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:55:34.779+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:55:34.780+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:55:34.780+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:55:34.789+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:55:34.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:55:34.789+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:55:34.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.047 seconds
[2023-08-23T23:56:05.531+0000] {processor.py:157} INFO - Started process (PID=10083) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:56:05.533+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:56:05.534+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:56:05.534+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:56:05.543+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:56:05.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:56:05.544+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:56:05.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.039 seconds
[2023-08-23T23:56:36.137+0000] {processor.py:157} INFO - Started process (PID=10148) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:56:36.138+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:56:36.139+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:56:36.138+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:56:36.145+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:56:36.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:56:36.146+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:56:36.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.035 seconds
[2023-08-23T23:57:06.401+0000] {processor.py:157} INFO - Started process (PID=10213) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:57:06.404+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:57:06.405+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:57:06.404+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:57:06.421+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:57:06.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:57:06.422+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:57:06.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.100 seconds
[2023-08-23T23:57:36.694+0000] {processor.py:157} INFO - Started process (PID=10278) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:57:36.694+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:57:36.695+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:57:36.695+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:57:36.703+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:57:36.701+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:57:36.704+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:57:36.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:58:07.037+0000] {processor.py:157} INFO - Started process (PID=10344) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:58:07.043+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:58:07.044+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:58:07.044+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:58:07.051+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:58:07.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:58:07.051+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:58:07.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.043 seconds
[2023-08-23T23:58:37.269+0000] {processor.py:157} INFO - Started process (PID=10409) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:58:37.270+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:58:37.270+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:58:37.270+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:58:37.278+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:58:37.276+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:58:37.278+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:58:37.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.038 seconds
[2023-08-23T23:59:07.557+0000] {processor.py:157} INFO - Started process (PID=10475) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:59:07.563+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:59:07.564+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:07.564+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:59:07.573+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:07.571+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/09_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/09_variable.py", line 16, in <module>
    bash_comand=f"echo variable: {{ var.value.token_sample }}",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-08-23T23:59:07.574+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:59:07.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.057 seconds
[2023-08-23T23:59:31.941+0000] {processor.py:157} INFO - Started process (PID=10530) to work on /opt/airflow/dags/09_variable.py
[2023-08-23T23:59:31.942+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/09_variable.py for tasks to queue
[2023-08-23T23:59:31.943+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:31.943+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/09_variable.py
[2023-08-23T23:59:31.953+0000] {processor.py:836} INFO - DAG(s) dict_keys(['09_variable']) retrieved from /opt/airflow/dags/09_variable.py
[2023-08-23T23:59:32.085+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:32.084+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:09_variable
[2023-08-23T23:59:32.105+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:32.105+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:09_variable
[2023-08-23T23:59:32.117+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:32.117+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:09_variable
[2023-08-23T23:59:32.141+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:32.140+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-23T23:59:32.169+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:32.169+0000] {dag.py:2763} INFO - Creating ORM DAG for 09_variable
[2023-08-23T23:59:32.191+0000] {logging_mixin.py:150} INFO - [2023-08-23T23:59:32.191+0000] {dag.py:3508} INFO - Setting next_dagrun for 09_variable to 2023-08-22T15:00:00+00:00, run_after=2023-08-23T15:00:00+00:00
[2023-08-23T23:59:32.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/09_variable.py took 0.283 seconds
